version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=clothing_store
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysqldb
    build: .
    restart: always
    ports:
      - 2000:2000
    environment:
      - PORT=2000
      - DB_HOST=mysqldb
      - DB_NAME=clothing_store
      - DB_USER=root
      - DB_PASS=1234
      - DB=mysql
      - BCRYPT_SALT=10
      - JWT_SECRET=thi uffgh kjj
      - EMAIL=${EMAIL}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_SERVICE=gmail
      - STRIPE_KEY=${STRIPE_KEY}
      - CLIENT_URL=localhost:3000

volumes: 
  db:



