version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=clothing_store
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysqldb
    build: .
    restart: always
    ports:
      - 2000:2000
    environment:
      - PORT=2000
      - DB_HOST=mysqldb
      - DB_NAME=clothing_store
      - DB_USER=root
      - DB_PASS=1234
      - DB=mysql
      - BCRYPT_SALT=10
      - JWT_SECRET=thi uffgh kjj
      - EMAIL={your email}
      - EMAIL_PASS={your email password}
      - EMAIL_SERVICE=gmail
      - STRIPE_KEY=sk_test_51HkkefDHNiYh4mtD1YXl3fpM6wfVvRTWD81ANICazNdPOYb2mwik18G4dbTNfZK0E7oJq7JbW5r5qXPHrRqS0lkI00VgwQTR2V
      - CLIENT_URL=localhost:3000

volumes: 
  db:



